---
- name: Execute command
  ansible.builtin.shell: "whois -h whois.radb.net -- '-i origin {{ asnet }}' | grep -Eo \"([0-9.]+){4}/[0-9]+\""
  register: networks

#- name: Debug
#  ansible.builtin.debug:
#    msg: "{{ networks }}"

- name: Add hosts to {{ tv_chain_name }} chain
  ansible.builtin.iptables:
    chain: "{{ tv_chain_name }}"
    source: "{{ item }}"
    jump: ACCEPT
    comment: "Allow from AS -> {{ asnet }}"
    action: insert
  loop: "{{ networks.stdout_lines | list }}"

